<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerBfc7gjC\AppTestDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerBfc7gjC/AppTestDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerBfc7gjC.legacy');

    return;
}

if (!\class_exists(AppTestDebugProjectContainer::class, false)) {
    \class_alias(\ContainerBfc7gjC\AppTestDebugProjectContainer::class, AppTestDebugProjectContainer::class, false);
}

return new \ContainerBfc7gjC\AppTestDebugProjectContainer(array(
    'container.build_hash' => 'Bfc7gjC',
    'container.build_id' => 'c084f0b0',
    'container.build_time' => 1539847791,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerBfc7gjC');
